In [10]:
import torch 

x = torch.rand(1,requires_grad=True)
print(x) 
y = x+2
print(y)
y = y * y * y
y.backward()
print(y)










tensor([0.1702], requires_grad=True)
tensor([2.1702], grad_fn=<AddBackward0>)
tensor([10.2207], grad_fn=<MulBackward0>)
